### ISSUE TITLE
Tweet failed: [{'message': 'Status is over 140 characters.', 'code': 186}]

### ISSUE THREAD

**Issue by WMSaj13** [BrianMitchL/weatherBot#25]
Example tweet over 140 character limit: 
_The forecast for today is mostly cloudy throughout the day and breezy starting in the afternoon, continuing until evening. 18ºC/13ºC. I want to believe._

**Comment by BrianMitchL** [comment]
That's a pretty long forecast, I'll try to find a way to gracefully truncate if it's too long, or skip the extra forecast text ("I want to believe" in this example).

**Comment by BrianMitchL** [comment]
I started work in #27, move conversation to there.
