### ISSUE TITLE
Use textwrap.shorten for tweets that are too long

### ISSUE THREAD

**Issue by BrianMitchL** [BrianMitchL/weatherBot#26]
[textwrap.shorten](https://docs.python.org/3.4/library/textwrap.html#textwrap.shorten) would be a great function to auto-truncate a tweet that is too long.

This wasn't added to the standard library until python 3.4, so this will require a breaking change.

**Comment by BrianMitchL** [comment]
This change would belong somewhere around https://github.com/BrianMitchL/weatherBot/blob/development/weatherBot.py#L231

**Comment by WTFox** [comment]
See PR https://github.com/WTFox/weatherBot/pull/1
