### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by BrianMitchL** [BrianMitchL/weatherBot#5]
Test coverage is poor to say the least. Improving test coverage to something closer to 75% would be awesome. Adding to version 1.1 milestone.

**Comment by bman4789** [comment]
- [ ] Mock responses from [python-forecast.io](https://github.com/ZeevG/python-forecast.io)
- [ ] Test variable location (always point to [@MorrisMNWeather](https://twitter.com/MorrisMNWeather) as it will always tweet from Morris, MN?)
- [ ] Increase test coverage to 75%
- [ ] Refactor code that will make it easier to test
- [ ] Remove old test code that is commented out

**Comment by BrianMitchL** [comment]
Coverage is now around 80%.
