### ISSUE TITLE
Dark Sky API no more new sign up mentioned in their website 

### ISSUE THREAD

**Issue by Tharun-tharun** [BrianMitchL/weatherBot#56]
How do I get dark sky API? it's asking for dark sky API is there any other alternative source to get API

**Comment by BrianMitchL** [comment]
Apple acquired Dark Sky and isn't allowing anyone to create new API keys. This project is near end-of-life, and I won't be putting much time into it anymore, sorry!

**Comment by ryanmr** [comment]
Since Dark Sky is EOL, you could consider another weather api, though it would take a fork and additional work to swap the implementation.

https://openweathermap.org/

**Comment by Tharun-tharun** [comment]
> Since Dark Sky is EOL, you could consider another weather API, though it would take a fork and additional work to swap the implementation.
> 
> https://openweathermap.org/

Thanks, man that helps, but do you want me to fork this project if I do that will you make changes to your project so that particular API will work after making some changes to it.
